import "@/app/globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { ThemeProvider } from "@/features/shared/theme-provider";

const montserrat = localFont({
  src: "./fonts/Montserrat-VariableFont_wght.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Rezervasyon Uygulaması",
  description: "Generated by Halime Gildan",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${montserrat.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
